### ISSUE TITLE
H2 Configuration is missing

### ISSUE THREAD

**Issue by marcDeSantis** [MonsantoCo/cf-portal#1]
The application fails to deploy due to a missing database configuration.

`ERR Configuration error: Configuration error[While loading datasource: could not find db.default in configuration]`

I was going to attempt to correct this myself, but considering the application.conf is in the .gitignore file (and not in this repo), I am assuming there are other configurations missing as well.

**Comment by mjseid** [comment]
Oops.  I've added the missing file, thanks for catching this!
